const ARTICLES = [
  {
    title: "How to get started with local AI (2026)",
    url: "how-to-get-started-local-ai.html",
    date: "2026-08-29",
    updated: "2026-08-29",
    category: "AI",
    featured: true,
    tags: ["Local AI", "Ollama", "Getting Started", "Beginner"],
    description: "How to get started with local AI in 2026 – pick the right hardware, install Ollama, download a model, and run it on your own machine. No cloud, no subscription, no jargon.",
    faq: [
      {
        q: "Can I run local AI on a laptop without a GPU?",
        a: "Yes. A modern laptop with 16 GB of RAM can run a 7B model at conversational speed via CPU-only inference. It won't be as fast as a GPU, but it's perfectly usable for chat, summarization, and coding assistance.",
      },
      {
        q: "Is local AI as good as ChatGPT?",
        a: "For many everyday tasks, yes. A 7B or 13B model running locally handles chat, summarization, and code generation well. The biggest models (70B+) are closer to frontier models but need more hardware.",
      },
      {
        q: "Do I need an internet connection to use local AI?",
        a: "No. Once the model is downloaded, everything runs entirely on your device. No internet needed, no data sent anywhere, no subscription.",
      },
    ],
  },
  {
    title: "DGX Spark vs RTX Spark vs Ryzen AI Halo: the 2026 local-AI desktop showdown",
    url: "dgx-spark-rtx-spark-ryzen-ai-halo.html",
    date: "2026-08-29",
    updated: "2026-08-29",
    category: "Hardware",
    featured: true,
    tags: ["AI Hardware", "GPU", "Local AI", "NVIDIA", "AMD"],
    description: "NVIDIA DGX Spark, NVIDIA RTX Spark, and AMD Ryzen AI Max (Strix Halo) — three ways to run local AI in 2026. Specs, what each is for, and which one you should buy.",
    faq: [
      {
        q: "Can these run AI models without an internet connection?",
        a: "Yes. That's the whole point of unified memory and on-device compute — models run locally with no cloud dependency and your data never leaves the machine.",
      },
      {
        q: "How much VRAM do they have?",
        a: "None in the traditional sense. All three use unified memory (up to 128 GB) shared between CPU and GPU, so the full memory is available for the model — far more than any consumer GPU's dedicated VRAM.",
      },
      {
        q: "Which is the best value for local AI?",
        a: "For price per gigabyte of unified memory, AMD's Ryzen AI Max (Strix Halo) mini PCs win at roughly ₹70k–1.1 lakh. NVIDIA's RTX Spark offers the best blend of performance, Windows compatibility, and gaming. DGX Spark is the most powerful but the most expensive.",
      },
    ],
  },
  {
    title: "Best GPU for running LLMs locally (2026)",
    url: "best-gpu-for-local-llm.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "Hardware",
    featured: true,
    tags: ["GPU", "LLM", "Local AI", "Benchmarks", "VelsTech Lab"],
    description: "The best GPUs for running LLMs locally in 2026 – RTX vs Radeon, how much VRAM you really need, and what actually matters for llama.cpp and Ollama.",
    faq: [
      {
        q: "How much VRAM do I need to run an LLM locally?",
        a: "For a 7B model at 4-bit quantization you want 8 GB; for 13–14B models 12–16 GB; and for 32B models 24 GB or more if you want to fit weights plus the KV cache in memory.",
      },
      {
        q: "NVIDIA or AMD GPU for local LLMs?",
        a: "NVIDIA (CUDA) has the smoothest setup with llama.cpp and Ollama. AMD (ROCm/Vulkan) works well too and often gives more VRAM per rupee, but needs slightly more tinkering.",
      },
      {
        q: "Is CPU-only inference worth it?",
        a: "For occasional use, yes – modern CPUs can run 7B models at a few tokens per second. For daily use, a GPU with 12 GB+ of VRAM is a much better experience.",
      },
    ],
  },
  {
    title: "How much VRAM do you need for 7B, 14B, and 32B models?",
    url: "how-much-vram-for-llm.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    tags: ["VRAM", "LLM", "GPU", "Quantization", "VelsTech Lab"],
    description: "VRAM needed for 7B, 14B, and 32B LLMs – weights, quantization, KV cache, and context length, with a quick-reference table.",
    faq: [
      {
        q: "What does quantization mean for VRAM?",
        a: "Quantization lowers the precision of the model's weights (e.g. from 16-bit to 4-bit), which shrinks the memory footprint. A 7B model at 4-bit takes roughly half the VRAM it does at 16-bit.",
      },
      {
        q: "Does a longer context window need more VRAM?",
        a: "Yes. The KV cache grows with context length, so a 32K context can add several GB of VRAM on top of the weights. Use a tool like the LLM VRAM calculator to check your exact setup.",
      },
    ],
  },
  {
    title: "Best GPU for AI under ₹50,000 (India, 2026)",
    url: "best-gpu-ai-under-50000.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "Hardware",
    tags: ["GPU", "Budget", "India", "Local AI", "VelsTech Lab"],
    description: "The best GPUs for AI under ₹50,000 in India – which cards actually fit the budget and can run local LLMs, with VRAM per rupee compared.",
    faq: [
      {
        q: "Can I run a local LLM on a GPU under ₹50,000?",
        a: "Yes. A 12 GB card in that budget (like a used Radeon RX 6800 XT or an RTX 3060 12GB) can run 7B–13B models comfortably at 4-bit quantization, and lighter 32B models with CPU offload.",
      },
      {
        q: "Should I buy new or used for the best VRAM per rupee?",
        a: "Used Radeon cards often win on raw VRAM per rupee, but check warranty and mining history. For the smoothest setup with the least tinkering, an NVIDIA card is usually easier to get working.",
      },
    ],
  },
  {
    title: "Xiaomi AI Cube: the mini desktop built for local AI",
    url: "xiaomi-ai-cube.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "Hardware",
    featured: true,
    tags: ["AI Hardware", "NPU", "Mini PC", "VelsTech Lab"],
    description: "Xiaomi's AI Cube is a small desktop with a big NPU – made to run LLMs locally. Here's what it is, what's inside, and whether it's worth buying.",
    faq: [
      {
        q: "What is an NPU and why does it matter?",
        a: "An NPU is a dedicated chip for AI workloads like running LLMs. It does what a GPU can but far more efficiently for inference, which is why the AI Cube can run models locally in a small, quiet, low-power desktop.",
      },
      {
        q: "Can I run AI on it without an internet connection?",
        a: "Yes – that's the point. Because the model runs on the device's NPU, you get private, offline AI with no data leaving your machine.",
      },
    ],
  },
  {
    title: "Qwen3.8 Flash Next: Alibaba's new fast reasoning model",
    url: "qwen3-8-flash-next.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    tags: ["LLM", "Qwen", "Reasoning"],
    description: "Qwen3.8 Flash Next is Alibaba's newest reasoning model – faster, cheaper, and smarter. Here's what changed, how it performs, and how it compares.",
  },
  {
    title: "GLM 5.3: what's new in Zhipu AI's latest model",
    url: "glm-5-3.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    tags: ["LLM", "GLM", "Benchmarks"],
    description: "GLM 5.3 is Zhipu AI's newest update – stronger reasoning, better coding, and competitive pricing. Here's what's new and who it's for.",
  },
  {
    title: "Omarchy: the beautiful, opinionated Linux distro everyone's talking about",
    url: "omarchy.html",
    date: "2026-08-26",
    updated: "2026-08-26",
    category: "Operating Systems",
    featured: true,
    tags: ["Linux", "Arch", "Distro"],
    description: "The Arch-based distro made by DHH of Basecamp – beautiful, opinionated, terminal-first. Here's what it is, why it's trending, and whether you should try it.",
  },
  {
    title: "What is machine learning, really?",
    url: "what-is-machine-learning.html",
    date: "2026-08-25",
    updated: "2026-08-25",
    category: "AI",
    tags: ["Basics", "ML"],
    description: "A plain-language look at what learning from data actually means – training, models, and prediction – without the jargon.",
  },
  {
    title: "What is a Large Language Model, really?",
    url: "what-is-an-llm.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "AI",
    tags: ["LLM", "Basics"],
    description: "A plain-language look at how LLMs work under the hood – tokens, context, and probabilities – without the jargon.",
    faq: [
      {
        q: "Is a large language model the same as artificial intelligence?",
        a: "No. An LLM is one kind of AI – a model trained to predict the next word. 'AI' is a much bigger umbrella that includes vision, robotics, and more.",
      },
      {
        q: "Do LLMs actually understand what they're saying?",
        a: "They don't reason the way a human does. They compute the most likely next token based on patterns in their training data, which often looks a lot like understanding.",
      },
    ],
  },
  {
    title: "How to write better prompts",
    url: "better-prompts.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "AI",
    tags: ["Prompting", "Tools"],
    description: "Practical prompting patterns that get better answers from ChatGPT, Claude, and similar tools.",
    faq: [
      {
        q: "Why is being specific in a prompt important?",
        a: "LLMs answer based on the words you give them. Clear, specific instructions narrow the answer space, so you get relevant output instead of a generic guess.",
      },
      {
        q: "What if the model ignores my instructions?",
        a: "Try breaking the request into steps, giving an example of the format you want, or asking it to work through the problem before answering.",
      },
    ],
  },
  {
    title: "Local vs cloud AI: which should you choose?",
    url: "local-vs-cloud-ai.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "AI",
    tags: ["Privacy", "Hardware"],
    description: "Privacy, cost, and capability – a comparison of running models on your own hardware versus cloud APIs.",
  },
  {
    title: "How to choose parts for your first PC build",
    url: "first-pc-build.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Hardware",
    tags: ["PC Build", "Guide"],
    description: "A beginner-friendly guide to picking a CPU, GPU, RAM, and storage that actually match how you'll use the PC.",
  },
  {
    title: "CPU vs GPU: what does each one do?",
    url: "cpu-vs-gpu.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Hardware",
    tags: ["Components", "Basics"],
    description: "Breaking down the two most important components in your machine and when each one matters most.",
  },
  {
    title: "SSD vs HDD: the upgrade that changes everything",
    url: "ssd-vs-hdd.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Hardware",
    tags: ["Storage", "Upgrade"],
    description: "Why an SSD makes an old computer feel new again, and how to pick the right drive and size.",
  },
  {
    title: "Linux for beginners: getting started",
    url: "linux-beginners.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Operating Systems",
    tags: ["Linux", "Beginners"],
    description: "Picking a distro, installing it, and surviving your first week without breaking anything.",
    faq: [
      {
        q: "Which Linux distro should a beginner choose?",
        a: "Ubuntu or Linux Mint are the most beginner-friendly – huge communities, tons of tutorials, and software that installs easily. Start there before trying Arch-based distros.",
      },
      {
        q: "Do I need to know how to use the terminal to use Linux?",
        a: "No. Modern distros work fine with a graphical interface. The terminal is a power tool you can learn gradually – grab the free Linux command cheat sheet to speed that up.",
      },
    ],
  },
  {
    title: "Essential terminal commands everyone should know",
    url: "terminal-commands.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Operating Systems",
    tags: ["Terminal", "Basics"],
    description: "Navigation, files, permissions, and package management – the commands you'll use every single day.",
  },
  {
    title: "Windows vs Linux: when to use which",
    url: "windows-vs-linux.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Operating Systems",
    tags: ["Linux", "Windows"],
    description: "An honest comparison of the two for daily use, gaming, and development work.",
  },
  {
    title: "How does the internet actually work?",
    url: "how-internet-works.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Networking",
    tags: ["Basics", "DNS"],
    description: "A straightforward walkthrough of IP addresses, DNS, and routing – the basics that make the internet tick.",
  },
  {
    title: "Setting up a domain and pointing it anywhere",
    url: "setup-domain.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Networking",
    tags: ["DNS", "Self-hosting"],
    description: "How to buy a domain, configure DNS records, and connect it to GitHub Pages, a VPS, or a home server.",
  },
  {
    title: "Self-hosting 101: what can you run at home?",
    url: "self-hosting-101.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Networking",
    tags: ["Self-hosting", "Projects"],
    description: "From a media server to a personal cloud – services you can run on a Raspberry Pi or old laptop.",
  },
  {
    title: "The only 5 security habits you really need",
    url: "security-habits.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Security & Privacy",
    tags: ["Basics", "Passwords"],
    description: "Passwords, two-factor authentication, updates, backups, and skepticism – the checklist that covers most risks.",
    faq: [
      {
        q: "What is the single most effective security habit?",
        a: "Use a password manager with unique passwords for every account, and turn on two-factor authentication everywhere it's available. That covers most real-world attacks.",
      },
      {
        q: "Is two-factor authentication really necessary?",
        a: "Yes. Even if a password leaks, a second factor like an authenticator app or security key stops most account takeovers cold.",
      },
    ],
  },
  {
    title: "Password managers: why you need one",
    url: "password-managers.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Security & Privacy",
    tags: ["Passwords", "Tools"],
    description: "How a password manager works, what to look for, and why reusing passwords is the biggest risk most people have.",
  },
  {
    title: "Spotting phishing attempts",
    url: "spotting-phishing.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Security & Privacy",
    tags: ["Phishing", "Awareness"],
    description: "Real examples of fake emails and messages, and the red flags that give them away before you click.",
  },
  {
    title: "How to start learning to code in 2026",
    url: "learn-to-code.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Programming & Web",
    tags: ["Beginners", "Roadmap"],
    description: "A realistic roadmap – pick a language, build tiny projects, and avoid the tutorial trap.",
  },
  {
    title: "HTML, CSS, and JavaScript: what does each one do?",
    url: "html-css-js.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Programming & Web",
    tags: ["Web", "Basics"],
    description: "The three building blocks of every website, explained with a simple analogy.",
  },
  {
    title: "Version control with Git for complete beginners",
    url: "git-beginners.html",
    date: "2026-08-24",
    updated: "2026-08-24",
    category: "Programming & Web",
    tags: ["Git", "Tools"],
    description: "Why every developer uses Git, and the handful of commands that cover 90% of daily work.",
  },
  {
    title: "Installing ROCm on Ubuntu for Radeon GPUs",
    url: "install-rocm-ubuntu.html",
    date: "2026-08-25",
    updated: "2026-08-25",
    category: "Tutorials",
    featured: true,
    tags: ["ROCm", "Radeon", "GPU"],
    description: "Step-by-step guide to installing ROCm 7.14 on Ubuntu 26.04 for AMD Radeon (RDNA2/RDNA3) GPUs – from apt setup to rocminfo verification.",
  },
  {
    title: "Installing PyTorch with ROCm on Radeon GPUs",
    url: "install-pytorch-rocm-ubuntu.html",
    date: "2026-08-25",
    updated: "2026-08-25",
    category: "Tutorials",
    tags: ["PyTorch", "ROCm", "Radeon"],
    description: "Step-by-step guide to installing PyTorch with ROCm support on Ubuntu for AMD Radeon (RDNA2) GPUs – venv setup, pip install, and GPU verification.",
  },
  {
    title: "Apple's new Mac desktops: Mac Studio M5 Max/Ultra and Mac mini M6/M5 Pro",
    url: "new-mac-desktops.html",
    date: "2026-08-25",
    updated: "2026-08-25",
    category: "Hardware",
    tags: ["Apple Silicon", "Mac", "Desktop"],
    featured: true,
    description: "Apple's compact desktops land on 22 September – the Mac Studio with M5 Max and M5 Ultra, plus the Mac mini with M6 and M5 Pro. Here's what changed and which one is yours.",
  },
  {
    title: "Qwen 27B Ridge 3.7bpw on RX 6800M: ROCm vs Vulkan at 16K – VelsTech Lab",
    url: "qwen-27b-ridge-rocm-vs-vulkan.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    featured: true,
    tags: ["VelsTech Lab", "Qwen", "RX 6800M", "ROCm", "Vulkan", "Benchmark"],
    description: "Tested Qwen 27B Ridge at 3.7bpw on a 12GB RX 6800M – ROCm 18.1 tok/s vs Vulkan 21.8 tok/s decode at 16K, with prompt-eval tradeoffs and VRAM fit.",
  },
  {
    title: "Ornith 35B MoE at 262K on RX 6800M: ROCm vs Vulkan – VelsTech Lab",
    url: "ornith-35b-moe-262k-rocm-vs-vulkan.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    featured: true,
    tags: ["VelsTech Lab", "MoE", "Ornith 35B", "RX 6800M", "ROCm", "Vulkan", "Benchmark"],
    description: "Tested Ornith 1.5 35B-A3B MoE at 262K on RX 6800M – ROCm 25.6 tok/s vs Vulkan 19.6 tok/s decode, 83 tok/s prompt, with 28 CPU experts and q8 KV.",
  },
  {
    title: "MoE vs Dense on RX 6800M: 3B Active vs 27B at 16K/262K – VelsTech Lab",
    url: "moe-vs-dense-rx6800m-16k-vs-262k.html",
    date: "2026-08-27",
    updated: "2026-08-27",
    category: "AI",
    featured: true,
    tags: ["VelsTech Lab", "MoE vs Dense", "RX 6800M", "Benchmark"],
    description: "Same RX 6800M 12GB – Ornith 35B MoE (3B active, 262K) vs Qwen 27B dense (27B, 16K) at q8 KV, ROCm vs Vulkan head-to-head.",
  },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = ARTICLES;
}
